[project]
name = 'smart-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.players]
path = 'contracts/players.clar'
clarity_version = 2
epoch = 2.5
[stacks]
node = "http://192.168.87.22:20443"
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
